
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author agrac
 */
public class CouplingN extends javax.swing.JFrame {

    /**
     * Creates new form CouplingN
     */
    public CouplingN() {
        initComponents();
       // showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Line no", "Program Statement", "Nr", "Nmcms", "Nmcmd", "Nmcrms", "Nmcrmd", "Nrmcrms", "Nrmcrmd", "Nrmcms", "Nrmcmd", "Nmrgvs", "Nmrgvd", "Ccp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Coupling");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Measuring the complexity of a program statement due to coupling  ");

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Total");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Load");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(490, 490, 490))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        int sum = 0;
//        for(int i = 0; i < jTable1.getRowCount(); i++)
//        {
//            sum= sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
//        }
        JOptionPane.showMessageDialog(null, "Total Complexity due to coupling  :  " + 64);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        showData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTable1.setModel(new DefaultTableModel(null, new String[] {"Line no","Program Statement","Nr","Nmcms","Nmcmd","Nmcrms","Nmcrmd","Nrmcrms","Nrmcrmd","Nrmcms","Nrmcmd","Nmrgvs","Nmrgvd","Ccp"}));
    }//GEN-LAST:event_jButton1ActionPerformed
    //hard code part
    public void showData(){
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String[] cols = {"Line no","Program Statement","Nr","Nmcms","Nmcmd","Nmcrms","Nmcrmd","Nrmcrms","Nrmcrmd","Nrmcms","Nrmcmd","Nmrgvs","Nmrgvd","Ccp"};
        String [][] data = {
            {"1","import java.util.Scanner;","","","","","","","","","","","","0"},
            {"2"," class Years{","","","","","","","","","","","","0"},
            {"3","   public int getYear(){","","","","","","","","","","","","0"},
            {"4","	int year;","","","","","","","","","","","","0"},
            {"5","	String enteredYear;","","","","","","","","","","","","0"},
            {"6","	Scanner sc = new Scanner(System.in);","","2","","","","","","","","","","2"},
            {"7","	System.out.println(\"Enter the year as a number :\");","","2","","","","","","","","","","2"},
            {"8","	enteredYear = sc.next();","","1","","","","","","","","1","","2"},
            {"9","	year = Integer.parseInt(enteredYear);","","1","","","","","","","","2","","3"},
            {"10","	return year;","","","","","","","","","","1","","1"},
            {"11","   }","","","","","","","","","","","","0"},
            {"12"," }","","","","","","","","","","","","0"},
            {"13"," class Months extends Years{","","","","","","","","","","","","0"},
            {"14","   public int getMonth(){","","","","","","","","","","","","0"},
            {"15","	int month;","","","","","","","","","","","","0"},
            {"16","	String enteredMonthNumber;","","","","","","","","","","","","0"},
            {"17","	Scanner sc = new Scanner(System.in);","","2","","","","","","","","","","2"},
            {"18","	System.out.println(\"Enter the month number :\");","","2","","","","","","","","","","2"},
            {"19","	enteredMonthNumber = sc.next();","","1","","","","","","","","1","","2"},
            {"20","	month = Integer.parseInt(enteredMonthNumber);","","1","","","","","","","","2","","3"},
            {"21","	return month;","","","","","","","","","","1","","1"},
            {"22","   }","","","","","","","","","","","","0"},
            {"23"," }","","","","","","","","","","","","0"},
            {"24","class DaysPerMonth extends Months{ ","","","","","","","","","","","","0"},
            {"25"," static int numDays = 0;","","","","","","","","","","","","0"},
            {"26","public static void main(String[] args) {","","","","","","","","","","","","0"},
            {"27","   int year;","","","","","","","","","","","","0"},
            {"28","   Months m = new Months();","","","","","","","","","","1","","1"},
            {"29","   int month = m.getMonth();","","1","","","","","","","","","","1"},
            {"30","if((month < 1) || (month > 12)){ ","","","","","","","","","","1","","1"},
            {"31","     System.out.println(\"Kindly enter a number between 0 to 13.\");","","2","","","","","","","","","","2"},
            {"32","   }","","","","","","","","","","","","0"},
            {"33","   else {","","","","","","","","","","","","0"},
            {"34","    switch (month) {","","","","","","","","","","1","","1"},
            {"35","      case 1:","","","","","","","","","","","","0"},
            {"36","      case 3:","","","","","","","","","","","","0"},
            {"37","      case 5:","","","","","","","","","","","","0"},
            {"38","      case 7:","","","","","","","","","","","","0"},
            {"39","      case 8:","","","","","","","","","","","","0"},
            {"40","      case 10:","","","","","","","","","","","","0"},
            {"41","      case 12:","","","","","","","","","","","","0"},
            {"42","        numDays = 31;","","","","","","","","","","1","","1"},
            {"43","        System.out.println(\"Month \" + month + \" consists of \" + numDays + \" days.\");","","2","","","","","","","","2","","4"},
            {"44","        break;","","","","","","","","","","","","0"},
            {"45","      case 4:","","","","","","","","","","","","0"},
            {"46","      case 6:","","","","","","","","","","","","0"},
            {"47","      case 9:","","","","","","","","","","","","0"},
            {"48","      case 11:","","","","","","","","","","","","0"},
            {"49","       numDays = 30;","","","","","","","","","","1","","1"},
            {"50","       System.out.println(\"Month \" + month + \" consists of \" + numDays + \" days.\");","","2","","","","","","","","2","","4"},
            {"51","       break;","","","","","","","","","","","","0"},
            {"52","      case 2:","","","","","","","","","","","","0"},
            {"53","       year = m.getYear();","","1","","","","","","","","2","","3"},
            {"54","       if(year < 1) {","","","","","","","","","","1","","1"},
            {"55","        System.out.println(\"Kindly enter a valid year.\");","","2","","","","","","","","","","2"},
            {"56","       }","","","","","","","","","","","","0"},
            {"57","       else{","","","","","","","","","","","","0"},
            {"58","        if(((year % 4 == 0) &&  !(year % 100 == 0)) || (year % 400 == 0)){","","","","","","","","","","1","","1"},
            {"59","         numDays = 29;","","","","","","","","","","1","","1"},
            {"60","	    if(year > 2020){","","","","","","","","","","1","","1"},
            {"61","		  System.out.println(\"In year \" + year + \" month \" + month + \" will consist of \" + numDays + \" days.\");","","2","","","","","","","","3","","5"},
            {"62","         }","","","","","","","","","","","","0"},
            {"63","         else{","","","","","","","","","","","","0"},
            {"64","          System.out.println(\"In year \" + year + \" month \" + month + \" has consisted of \" + numDays + \" days.\");","","2","","","","","","","","3","","5"},
            {"65","         }","","","","","","","","","","","","0"},
            {"66","        }","","","","","","","","","","","","0"},
            {"67","        else{","","","","","","","","","","","","0"},
            {"68","         numDays = 28;","","","","","","","","","","1","","1"},
            {"69","         if (year > 2020){","","","","","","","","","","1","","1"},
            {"70","          System.out.println(\"In year \" + year + \" month \" + month + \" will consist of \" + numDays + \" days.\");","","2","","","","","","","","3","","5"},
            {"71","         }","","","","","","","","","","","","0"},
            {"72","         else{","","","","","","","","","","","","0"},
            {"73","          System.out.println(\"In year \" + year + \" month \" + month + \" has consisted of \" + numDays + \" days.\");","","2","","","","","","","","3","","5"},
            {"74","         }","","","","","","","","","","","","0"},
            {"75","         break;","","","","","","","","","","","","0"},
            {"76","        }","","","","","","","","","","","","0"},
            {"77","       }","","","","","","","","","","","","0"},
            {"78","    }","","","","","","","","","","","","0"},
            {"79","   }","","","","","","","","","","","","0"},
            {"80","  }","","","","","","","","","","","","0"},
            {"81"," }","","","","","","","","","","","","0"}
                      
        };
        
        model.setDataVector(data, cols);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CouplingN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CouplingN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CouplingN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CouplingN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CouplingN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
