
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Samanmali
 */
public class Inherit extends javax.swing.JFrame {

    /**
     * Creates new form Inherit
     */
    public Inherit() {
        initComponents();
        //showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Count", "Class Name", "No Of Direct Inheritance", "No of Indirect Inheritance", "Total Inheritance", "Ci"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Load data in table view");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Total ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //hard code part
    public void showData(){
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String[] cols = {"Count","Class Name","No Of Direct Inheritance","No Of Indirect Inheritance","Total Inheritance","Ci"};
        String [][] data = {
                            {"1","import java.util.Scanner","0","0","0","0"},
                            {"2","class Years","0","0","0","0"},
                            {"3","public int getYear(){","0","0","0","0"},
                            {"4","int year;","0","0","0","0"},
                            {"5","String enteredYear;","0","0","0","0"},
                            {"6","Scanner sc = new Scanner(System.in);","0","0","0","0"},
                            {"7","System.out.println(\"Enter the year as a number :\");","0","0","0","0"},
                            {"8","enteredYear = sc.next();","0","0","0","0"},
                            {"9","year = Integer.parseInt(enteredYear);","0","0","0","0"},
                            {"10","return year;","0","0","0","0"},
                            {"11","}","0","0","0","0"},
                            {"12","}","0","0","0","0"},
                            {"13","class Months extends Years{","1","0","1","1"},
                            {"14","public int getMonth(){","0","0","0","0"},
                            {"15","int month;","0","0","0","0"},
                            {"16","String enteredMonthNumber;","0","0","0","0"},
                            {"17","Scanner sc = new Scanner(System.in);","0","0","0","0"},
                            {"18","System.out.println(\"Enter the month number :\");","0","0","0","0"},
                            {"19","enteredMonthNumber = sc.next();","0","0","0","0"},
                            {"20","month = Integer.parseInt(enteredMonthNumber);","0","0","0","0"},
                            {"21","return month;","0","0","0","0"},
                            {"22","}","0","0","0","0"},
                            {"23","}","1","0","1","1"},
                            {"24","class DaysPerMonth extends Months{","1","0","0","1"},
                            {"25","static int numDays = 0;","0","0","0","0"},
                            {"26","public static void main(String[] args) {","0","0","0","0"},
                            {"27","int year;","0","0","0","0"},
                            {"28","Months m = new Months();","0","0","0","0"},
                            {"29","int month = m.getMonth();","0","0","0","0"},
                            {"30","if((month < 1) || (month > 12)){ ","0","0","0","0"},
                            {"31","System.out.println(\"Kindly enter a number between 0 to 13.\");","0","0","0","0"},
                            {"32","}","0","0","0","0"},
                            {"33","else {","0","0","0","0"},
                            {"34","switch (month) {","0","0","0","0"},
                            {"35","case 1:","0","0","0","0"},
                            {"36","case 3:","0","0","0","0"},
                            {"37","case 5:","0","0","0","0"},
                            {"38","case 7:","0","0","0","0"},
                            {"29","case 8:","0","0","0","0"},
                            {"40","case 10:","0","0","0","0"},
                            {"41","case 12:","0","0","0","0"},
                            {"32","numDays = 31;","0","0","0","0"},
                            {"43","System.out.println(\"Month \" + month + \" consists of \" + numDays + \" days.\");","0","0","0","0"},
                            {"44","break;","0","0","0","0"},
                            {"45","case 4:","0","0","0","0"},
                            {"46","case 6:","0","0","0","0"},
                            {"47","case 9:","0","0","0","0"},
                            {"48","case 11:","0","0","0","0"},
                            {"49","numDays = 30;","0","0","0","0"},
                            {"50","System.out.println(\"Month \" + month + \" consists of \" + numDays + \" days.\");","0","0","0","0"},
                            {"51","break;","0","0","0","0"},
                            {"52","case 2:","0","0","0","0"},
                            {"53","year = m.getYear();","0","0","0","0"},
                            {"54","if(year < 1) {","0","0","0","0"},
                            {"55","System.out.println(\"Kindly enter a valid year.\");","0","0","0","0"},
                            {"56","}","0","0","0","0"},
                            {"57","else{","0","0","0","0"},
                            {"58","if(((year % 4 == 0) &&  !(year % 100 == 0)) || (year % 400 == 0)){","0","0","0","0"},
                            {"59","numDays = 29;","0","0","0","0"},
                            {"60","if(year > 2020){","0","0","0","0"},
                            {"61","System.out.println(\"In year \" + year + \" month \" + month + \" will consist of \" + numDays + \" days.\");","0","0","0","0"},
                            {"62","}","0","0","0","0"},
                            {"63","else{","0","0","0","0"},
                            {"64","System.out.println(\"In year \" + year + \" month \" + month + \" has consisted of \" + numDays + \" days.\");","","0","",""},
                            {"65","}","0","0","0","0"},
                            {"66","}","0","0","0","0"},
                            {"67","else{","0","0","0","0"},
                            {"68","numDays = 28;","0","0","0","0"},
                            {"69","if (year > 2020){","0","0","0","0"},
                            {"70","System.out.println(\"In year \" + year + \" month \" + month + \" will consist of \" + numDays + \" days.\");","0","0","0","0"},
                            {"71","}","0","0","0","0"},
                            {"72","else{","0","0","0","0"},
                            {"73","System.out.println(\"In year \" + year + \" month \" + month + \" has consisted of \" + numDays + \" days.\");","0","0","0","0"},
                            {"74","}","0","0","0","0"},
                            {"75","break;","0","0","0","0"},
                            {"76","}","0","0","0","0"},
                            {"77","}","0","0","0","0"},
                            {"78","}","0","0","0","0"},
                            {"79","}","0","0","0","0"},
                            {"80","}","0","0","0","0"},
                            {"81","}","0","0","0","0"},
                           };
        
        model.setDataVector(data, cols);
        
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        showData();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Total complexity due to inheritance: "+2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTable1.setModel(new DefaultTableModel(null,new String[] {"Count","Class Name","No Of Direct Inheritance","No Of Indirect Inheritance","Total Inheritance","Ci"}) );
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inherit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inherit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inherit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inherit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inherit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
